groups:
  - name: guiding
    rules:
    # TODO remove "inst" when have swapped away from old log-exporter version (metric overlap)
    - record: guiding:status:is_stopped
      expr: phd2_status{status="Stopped",inst!=""}
    - record: guiding:status:is_calibrating
      expr: phd2_status{status="Calibrating",inst!=""}
    - record: guiding:status:is_settling
      expr: phd2_status{status="Settling",inst!=""}
    - record: guiding:status:is_guiding
      expr: phd2_status{status="Guiding",inst!=""}
    - record: guiding:status:was_guiding
      expr: max_over_time(phd2_status{status="Guiding",inst!=""}[10m])

    - record: guiding:status:is_connected
      expr: clamp(rate(phd2_total{inst!=""}[30s])>0,1,1)
    - record: guiding:status:was_connected
      expr: clamp(rate(phd2_total{inst!=""}[10m])>0,1,1)

    - record: guiding:status:lost_stars
      expr: sgn(rate(phd2_StarLost_total[2m]))>0

    - record: guiding:rms:ra:arcsec
      expr: phd2_rms{scale="arcsec",source="RADistanceRaw"}
    - record: guiding:rms:dec:arcsec
      expr: phd2_rms{scale="arcsec",source="DECDistanceRaw"}
    - record: guiding:rms:total:arcsec
      expr: phd2_rms{scale="arcsec",source="TotalDistanceRaw"}

    - record: guiding:rms:ra:px
      expr: phd2_rms{scale="px",source="RADistanceRaw"}
    - record: guiding:rms:dec:px
      expr: phd2_rms{scale="px",source="DECDistanceRaw"}
    - record: guiding:rms:total:px
      expr: phd2_rms{scale="px",source="TotalDistanceRaw"}

    - record: guiding:drift:ra
      expr: phd2_GuideStep_RADistanceRaw * on(instance) phd2_status{status="Guiding"} * on() ((rate(phd2_GuidingDithered_total[45s]) == bool 0) or on() absent(phd2_GuidingDithered_total))
    - record: guiding:drift:dec
      expr: phd2_GuideStep_DECDistanceRaw * on(instance) phd2_status{status="Guiding"} * on() ((rate(phd2_GuidingDithered_total[45s]) == bool 0) or on() absent(phd2_GuidingDithered_total))